### PR TITLE
Support for min/max parameters for splitter

### PR DESCRIPTION
**Pull request by msemelman**
Improved revision of previous pull request.

### CODE REVIEW

**Comment by msemelman** [comment]
@llvtt Have you seen this one?

**Comment by llvtt** [comment]
Yes, I've taken a look. These changes look fine to me; I'm discussing them
with my team.

On Wed, Aug 19, 2015 at 12:56 PM, Mariano Semelman <notifications@github.com

**Comment by msemelman** [comment]
Thank you, I didn't want to be annoying in any moment, is just that this has been proved to be very useful. Specially for datasets with bazzilion documents.
Godspeed =)

**Comment by llvtt** [comment]
This pull request was merged some time ago: https://github.com/mongodb/mongo-hadoop/commit/7be32b3f35e1fc88f809c39d7623603d24fe1bd0. Sorry for the late update.

**Pull request closed without merging**
